print(1)
raise ValueError("Invalid Value!")
print(2)

