try:
	num = 5 / 0
except:
	print("An error occurred")
#	raise # Re-raise the exception

